blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/Geoplateforme/plugin-qgis-gpf-isochrone-isodistance-itineraire/
    about: Please read carefully the documentation before to submit an issue.
