name: "🎳 Tester"

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/tester.yml
      - requirements/testing.txt

  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/tester.yml
      - requirements/testing.txt

env:
  PROJECT_FOLDER: "gpf_isochrone_isodistance_itineraire"
  PYTHON_VERSION: 3.9

jobs:
  tests-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          cache-dependency-path: "requirements/testing.txt"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/testing.txt

      - name: Run Unit tests
        run: pytest -p no:qgis tests/unit/

  test-qgis:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis:3.40-noble
      env:
        CI: true
        DISPLAY: ":1"
        MUTE_LOGS: true
        NO_MODALS: 1
        PYTHONPATH: "/usr/share/qgis/python/plugins:/usr/share/qgis/python:."
        QT_QPA_PLATFORM: "offscreen"
        WITH_PYTHON_PEP: false
      options: -v /tmp/.X11-unix:/tmp/.X11-unix -v ${{ github.workspace }}:~/$PROJECT_FOLDER

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Print QGIS version
        run: qgis --version

      - name: Install Python requirements
        run: |
          apt install -y python3-packaging python3-pip python3-pytest python3-setuptools python3-venv python3-wheel
          # # Create a virtual environment
          # cd ~
          # python3 -m venv --system-site-packages .venv
          # # Activate the virtual environment
          # source .venv/bin/activate
          # # Install the requirements
          # python3 -m pip install -U -r requirements/testing.txt

      - name: Run Unit tests
        run: |
          cd ~/${{ env.PROJECT_FOLDER }}
          xvfb-run python3 -m pytest tests/qgis --junitxml=junit/test-results-qgis.xml --cov-report=xml:coverage-reports/coverage-qgis.xml
